<?php

namespace recranet\craftrecranetbooking\elements;

use Craft;
use craft\base\Element;
use craft\elements\User;
use craft\elements\conditions\ElementConditionInterface;
use craft\elements\db\ElementQueryInterface;
use craft\helpers\UrlHelper;
use craft\web\CpScreenResponseBehavior;
use recranet\craftrecranetbooking\elements\conditions\AccommodationCondition;
use recranet\craftrecranetbooking\elements\db\AccommodationQuery;
use recranet\craftrecranetbooking\records\Accommodation as AccommodationRecord;
use yii\web\Response;

/**
 * Accommodation element type
 */
class Accommodation extends Element
{
    public int $recranetBookingId = 0;
    public null|string $slug = '';
    public null|string $slugDe = '';
    public null|string $slugEn = '';
    public null|string $slugFr = '';
    public null|string $titleDe = '';
    public null|string $titleEn = '';
    public null|string $titleFr = '';

    public function searchKeywords(string $attribute): string
    {
        return parent::searchKeywords($attribute); // TODO: Change the autogenerated stub
    }

    protected static function defineSearchableAttributes(): array
    {
        return ['title', 'slug', 'slugDe', 'slugEn', 'slugFr', 'titleDe', 'titleEn', 'titleFr'];
    }

    public static function displayName(): string
    {
        return Craft::t('_recranet-booking', 'Accommodation');
    }

    public static function lowerDisplayName(): string
    {
        return Craft::t('_recranet-booking', 'accommodation');
    }

    public static function pluralDisplayName(): string
    {
        return Craft::t('_recranet-booking', 'Accommodations');
    }

    public static function pluralLowerDisplayName(): string
    {
        return Craft::t('_recranet-booking', 'accommodations');
    }

    public static function refHandle(): ?string
    {
        return 'accommodation';
    }

    public static function trackChanges(): bool
    {
        return true;
    }

    public static function hasTitles(): bool
    {
        return true;
    }

    public static function hasUris(): bool
    {
        return false;
    }

    public static function isLocalized(): bool
    {
        return false;
    }

    public static function hasStatuses(): bool
    {
        return true;
    }

    public static function find(): ElementQueryInterface
    {
        return new AccommodationQuery(static::class);
    }

    public static function createCondition(): ElementConditionInterface
    {
        return Craft::createObject(AccommodationCondition::class, [static::class]);
    }

    protected static function defineSources(string $context): array
    {
        return [
            [
                'key' => '*',
                'label' => Craft::t('_recranet-booking', 'All accommodations'),
            ],
        ];
    }

    protected static function defineActions(string $source): array
    {
        // List any bulk element actions here
        return [];
    }

    protected static function includeSetStatusAction(): bool
    {
        return true;
    }

    protected static function defineSortOptions(): array
    {
        return [
            'title' => Craft::t('app', 'Title'),
            'slug' => Craft::t('app', 'Slug'),
            'uri' => Craft::t('app', 'URI'),
            [
                'label' => Craft::t('app', 'Date Created'),
                'orderBy' => 'elements.dateCreated',
                'attribute' => 'dateCreated',
                'defaultDir' => 'desc',
            ],
            [
                'label' => Craft::t('app', 'Date Updated'),
                'orderBy' => 'elements.dateUpdated',
                'attribute' => 'dateUpdated',
                'defaultDir' => 'desc',
            ],
            [
                'label' => Craft::t('app', 'ID'),
                'orderBy' => 'elements.id',
                'attribute' => 'id',
            ],
            // ...
        ];
    }

    protected static function defineTableAttributes(): array
    {
        return [
            'recranetBookingId' => ['label' => Craft::t('app', 'Recranet Booking ID')],
            'slug' => ['label' => Craft::t('app', 'Slug')],
            'slugDe' => ['label' => Craft::t('app', 'Slug (DE)')],
            'slugEn' => ['label' => Craft::t('app', 'Slug (EN)')],
            'slugFr' => ['label' => Craft::t('app', 'Slug (FR)')],
            'titleDe' => ['label' => Craft::t('app', 'Title (DE)')],
            'titleEn' => ['label' => Craft::t('app', 'Title (EN)')],
            'titleFr' => ['label' => Craft::t('app', 'Title (FR)')],
            'uri' => ['label' => Craft::t('app', 'URI')],
            'link' => ['label' => Craft::t('app', 'Link'), 'icon' => 'world'],
            'id' => ['label' => Craft::t('app', 'ID')],
            'uid' => ['label' => Craft::t('app', 'UID')],
            'dateCreated' => ['label' => Craft::t('app', 'Date Created')],
            'dateUpdated' => ['label' => Craft::t('app', 'Date Updated')],
            // ...
        ];
    }

    protected static function defineDefaultTableAttributes(string $source): array
    {
        return [
            'dateCreated',
            'dateUpdated',
            'recranetBookingId',
            'slug',
            'slugDe',
            'slugEn',
            'slugFr',
            'titleDe',
            'titleEn',
            'titleFr',
        ];
    }

    protected function defineRules(): array
    {
        return array_merge(parent::defineRules(), [
            // ...
        ]);
    }

    public function getUriFormat(): ?string
    {
        // If accommodations should have URLs, define their URI format here
        return null;
    }

    protected function previewTargets(): array
    {
        $previewTargets = [];
        $url = $this->getUrl();
        if ($url) {
            $previewTargets[] = [
                'label' => Craft::t('app', 'Primary {type} page', [
                    'type' => self::lowerDisplayName(),
                ]),
                'url' => $url,
            ];
        }
        return $previewTargets;
    }

    protected function route(): array|string|null
    {
        // Define how accommodations should be routed when their URLs are requested
        return [
            'templates/render',
            [
                'template' => 'site/template/path',
                'variables' => ['accommodation' => $this],
            ]
        ];
    }

    public function canView(User $user): bool
    {
        if (parent::canView($user)) {
            return true;
        }
        // todo: implement user permissions
        return $user->can('viewAccommodations');
    }

    public function canSave(User $user): bool
    {
        if (parent::canSave($user)) {
            return true;
        }
        // todo: implement user permissions
        return $user->can('saveAccommodations');
    }

    public function canDuplicate(User $user): bool
    {
        if (parent::canDuplicate($user)) {
            return true;
        }
        // todo: implement user permissions
        return $user->can('saveAccommodations');
    }

    public function canDelete(User $user): bool
    {
        if (parent::canSave($user)) {
            return true;
        }
        // todo: implement user permissions
        return $user->can('deleteAccommodations');
    }

    public function canCreateDrafts(User $user): bool
    {
        return true;
    }

    protected function cpEditUrl(): ?string
    {
        return null;
    }

    public function getPostEditUrl(): ?string
    {
        return UrlHelper::cpUrl('accommodations');
    }

    public function prepareEditScreen(Response $response, string $containerId): void
    {
        /** @var Response|CpScreenResponseBehavior $response */
        $response->crumbs([
            [
                'label' => self::pluralDisplayName(),
                'url' => UrlHelper::cpUrl('accommodations'),
            ],
        ]);
    }

    public function afterSave(bool $isNew): void
    {
        if (!$this->propagating) {
            $record = AccommodationRecord::findOne($this->id);
            if (!$record) {
                $record = new AccommodationRecord();
                $record->id = $this->id;
            }

            $record->title = $this->title;
            $record->recranetBookingId = $this->recranetBookingId;

            $record->slug = $this->slug;
            $record->slugDe = $this->slugDe;
            $record->slugEn = $this->slugEn;
            $record->slugFr = $this->slugFr;

            $record->titleDe = $this->titleDe;
            $record->titleEn = $this->titleEn;
            $record->titleFr = $this->titleFr;

            $record->save();
        }

        parent::afterSave($isNew);
    }

    public function afterDelete(): void
    {
        parent::afterDelete();

        Craft::$app->db->createCommand()
            ->delete('{{%_recranet-booking_accommodations}}', ['recranetBookingId' => $this->recranetBookingId])
            ->execute();
    }
}
